### ISSUE TITLE
PEP 541: Transfer of ownership of namesquatted package "age"

### ISSUE THREAD

**Issue by jojonas** [pypa/pypi-support#40] opened 2019-10-18 23:12 UTC
Hello, 

I would like to request that the `age` project (https://pypi.org/project/age/) on PyPI is transferred to PyPI user `jojonas` (me).

The `age` project on PyPI has been registered (and released once) in May 2015. This one existing release with version number 0.0 seems to be empty. There has not been any activity afterwards.
Furthermore, I could not find any contact details for current owner "duerrp". As far as I understood PEP 541, this counts as "name squatting", rendering the project name "invalid".

I would like to publish my own project (https://github.com/jojonas/pyage) under that name.

Thank you very much!

**Comment by yeraydiazdiaz** [comment] 2019-12-14 18:09
Hello @jojonas, I can confirm the `age` project has a single empty release and therefore can be considered invalid.

I will now ask an admin to perform the transfer.

**Comment by ewdurbin** [comment] 2019-12-19 16:54
transfer complete.

**Comment by jojonas** [comment] 2020-02-10 12:24
Hi @ewdurbin, I can't seem to find the transferred project. Is it supposed to show up at https://pypi.org/manage/projects/ ?

**Comment by jamadden** [comment] 2020-02-10 15:27
It looks like this may have been closed by mistake. I don't see any evidence in the project journal that this was transferred.

**Comment by ewdurbin** [comment] 2020-02-12 16:45
My apologies! Transfer _actually_ complete now.

**Closed by ewdurbin** 2020-02-12 16:45 UTC
Labels: PEP 541
