### ISSUE TITLE
PEP 541 Request: Phyra

### ISSUE THREAD

**Issue by LyQuid12** [pypa/pypi-support#2363] opened 2022-11-06 10:57 UTC
### Project to be claimed

`Phyra`: https://pypi.org/project/Phyra

### Your PyPI username

`LyQuid`: https://pypi.org/user/LyQuid

### Reasons for the request

I want to create a new project with the same name but different functions. This is my project as well as I am the maintainer, but because this project already has several versions, I can't publish my new project from the earliest version.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/EterNomm/Phyra-CLI

### Contact and additional research

I am the owner and maintainer, it should be allowed :]

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment] 2023-01-01 18:17
Hi @LyQuid12, that is the intended behaviour of PyPI, you cannot overwrite previously published files as they are considered immutable.

I suggest starting from a new major version and deleting old releases, or renaming your new project entirely.

Closing as no transfer is possible.

**Closed by yeraydiazdiaz** 2023-01-01 18:17 UTC
Labels: PEP 541
