### ISSUE TITLE
Project Limit Request: duckdb - 100 GB

### ISSUE THREAD

**Issue by hannes** [pypa/pypi-support#1129] opened 2021-06-01 19:59 UTC
### Project

https://pypi.org/p/duckdb

### Does this project already exist?

- [X] Yes

### Size of release/project

100 GB

### Which indexes

PyPI

### Reasons for the request

We upload dev versions to PyPI as well, and since we sometimes go through lots of those between releases, the project size balloons until the release happens and we clean up dev versions. This cleaning up of dev versions is currently done by script, but perhaps is also something PyPI could do? Anyway, to stop our CI breaking towards the end of a dev cycle It would be great if you could increase our limit. Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment] 2021-06-03 22:06
Can you explain what this project is, and why it's so large? Why publish dev releases to PyPI if they are later removed?

**Comment by hannesmuehleisen** [comment] 2021-06-04 05:19
Well I would not remove them were it not for the limits. The project is a in-process database engine similar to SQLite but tailored towards analytical workloads. We ship the entire database kernel in the package to avoid external dependencies, and we do so for many platforms. So while the individual package is rather small, the combinations of Python version, OS, architecture etc. create this large size.

**Comment by pradyunsg** [comment] 2021-06-04 09:13
https://github.com/duckdb/duckdb/blob/master/.github/workflows/main.yml#L832

The project seems to be uploading a release on every commit to their main git branch (i.e. every PR is released as a dev release).

**Comment by pradyunsg** [comment] 2021-09-15 08:12
IMO it is not reasonable to use PyPI as dump for artifacts that are generated on each commit to the default branch of the project. I'm inclined to say that we should reject this limit request.

Could you provide context for why you are publishing each commit of a project to PyPI?

**Comment by pradyunsg** [comment] 2021-12-05 20:08
A gentle nudge for @hannesmuehleisen, since this ticket is currently waiting on a response.

**Comment by hannesmuehleisen** [comment] 2021-12-06 05:24
We do not push each commit, but each PR merge. These are typically larger features that we want to allow people to install using their current workflow. Regardless of whether we push PRs or not, we are going to run out of PyPI space in about 20 versions at the current rate (which is going to increase because of more alive Python version and M1 support that is upcoming.)

**Comment by pradyunsg** [comment] 2022-01-15 08:59
I'm gonna defer @pypa/warehouse-admins on this one.

**Comment by Alex-Monahan** [comment] 2022-02-03 14:08
Hello pypa folks! 

Thank you for the work you do to enable the magic of Python! I wanted to add a few details here about why a size increase for this repo would be a great help to the Python community.

DuckDB is designed to lower the barrier to entry for analysts to use fast SQL queries in their workloads. Our target audience typically does not have compiler experience. By hosting dev versions (generated per PR not per commit), our Python users can test out bug fixes and new features without needing to learn how to compile the project. This allows us to bring Python folks (like myself - I don't know how to compile C++!) into the DuckDB community to help test it out prior to releases.

DuckDB is also considered to be a [popular and active project on snyk](https://snyk.io/advisor/python/duckdb), so this expanded pypi repo space would be useful to thousands of people!

We already do regular cleanup of these dev versions after each release, so we do try to be good stewards of pypi's resources. However, as Hannes stated above, even without these dev versions, we will run out of space in well under 20 releases and DuckDB releases every 1-2 months. That doesn't give us a lot of time until we are in a similar position asking for your help again.

Thank you for your consideration - we do really appreciate it!

**Comment by Alex-Monahan** [comment] 2022-02-03 14:17
> I'm gonna defer @pypa/warehouse-admins on this one.

I also reviewed your guidelines in the readme, and I believe that we fit within the guidelines that you outlined. I do recognize that they are guidelines and you have the ability to decide, but we really do believe we are following the spirit of your requirements. We recognize and appreciate the work you do for Python! 

We do not release nightly, for example, and the main reason for our large bundle size is compatibility across many platforms. We also do not ship another language within the package or any pre-trained ML models. The DuckDB organization is also well established and we have a number of happy pypi users!

**Comment by pradyunsg** [comment] 2022-02-03 21:37
The current project size limit for duckdb is 10 GB. It's not clear to me what's being requested here.

**Comment by Alex-Monahan** [comment] 2022-02-03 22:03
> The current project size limit for duckdb is 10 GB. It's not clear to me what's being requested here.

Hello!
The title of the issue was initially set to 100GB, so we are requesting a total of 100 GB of space. Could you grant us a 100GB allocation please? We appreciate it!

**Comment by hannesmuehleisen** [comment] 2022-02-04 05:58
We realise things cost money. To offset the increased cost of the hosting for our package, I've just setup recurring yearly donation of 99$ to the Python software foundation. I hope this can be resolved.

<img width="764" alt="Screenshot 2022-02-04 at 06 56 54" src="https://user-images.githubusercontent.com/227792/152479966-f84432b2-1955-4e5a-9ffc-125a296cefae.png">

**Comment by ewdurbin** [comment] 2022-02-04 15:19
Current usage for the project is 3.3 GiB, with a 100 MiB, and a 10.0 GiB total project size.

Are you anticipating reaching the 10.0 GiB limit in the near future? I'm also confused.

**Comment by Alex-Monahan** [comment] 2022-02-04 15:32
> Current usage for the project is 3.3 GiB, with a 100 MiB file size limit, and a 10.0 GiB total project size limit.
> 
> Are you anticipating reaching the 10.0 GiB limit in the near future? I'm also confused.

We just manually deleted some development releases in order to make room for our deployments to start working again. We had encountered errors due to running out of space and had to disable our pypi uploads. 

Would you mind granting us the space so we can avoid these issues? We do clean up our development releases periodically, but the current space is very limiting (and will cause issues even for production releases in the next few months as we continue roughly monthly releases). 

Are there any other details that you would like me to provide?

**Comment by pradyunsg** [comment] 2022-02-15 07:02
Updated the title and body to reflect the updated total size request. I'll defer to the admins on bumping the limit.

**Comment by hannesmuehleisen** [comment] 2022-02-21 09:47
We just ran into the limit again.

**Comment by hannes** [comment] 2022-03-21 09:04
And again. Any update on this?

**Comment by hannes** [comment] 2022-03-21 09:06
We are now ca. 15 versions away from running out of space *without considering any pre-releases*

**Comment by hannes** [comment] 2022-06-05 10:19
We have automated the removal of outdated dev releases

**Comment by adriangb** [comment] 2022-08-29 17:17
I've started using DuckDB and since it's a new project have run into a couple bugs / features that I wanted from trunk that are not in the last release version. Installing a nightly build (without having to fetch, compile, etc.) is really useful.

> DuckDB changes the frequency of dev releases from per-PR to "nightly at most" -- cut a release at some time each day, assuming that commits have landed in the previous 24 hours. DuckDB also continues their existing practice of culling those dev releases following a "proper" release.

It sounds like @hannes already automated cleaning out old dev releases. As an external observer it seems like the nightly (not every commit) upload cadence, cleaning out pre releases every production release / every X weeks plus a reasonable quota increase is a decent compromise on both sides.

**Comment by hannes** [comment] 2022-09-10 04:26
Thanks @adriangb  we have indeed automated the deletion. We are not very far off now from running out of space with just the regular releases. So could we please (please) get the quota increased?

**Comment by Mytherin** [comment] 2022-12-21 09:19
@di Unfortunately the issue is not yet resolved - while we are currently automatically deleting pre-releases and only keeping 2~3 active at a time, we are getting very close to the 10GB project size limit even without factoring in the pre-releases. As we are providing wheel builds for many platforms that pypi supports the individual releases are large (around 650MB per release). At this rate, we will be running out of space for our regular releases as well in a a few months and will be forced to start deleting actual releases. We would really like to avoid doing that as we know there are people still relying on older versions of DuckDB.

Could the maintainers please have another look at this and reconsider raising our limit?

**Comment by di** [comment] 2022-12-21 13:06
I've set the total project size limit to 30GB for now. If the project approaches this new limit, we can revisit. Please continue removing dev releases as much as possible. Thanks!

**Closed by di** 2022-12-21 13:06 UTC
Labels: limit request

**Comment by Mytherin** [comment] 2022-12-21 13:11
That's great news, thank you very much!
