### ISSUE TITLE
PEP 541 Request: scheduler

### ISSUE THREAD

**Issue by DigonIO** [pypa/pypi-support#1115] opened 2021-05-28 02:16 UTC
### Project to be claimed

`scheduler`: https://pypi.org/project/scheduler/

### Your PyPI username

`DigonIO`: https://pypi.org/user/DigonIO/

### Reasons for the request

Hello,

I would like to request the release of the package named `scheduler` in order to run a project under this name.
There is no project on PyPi, but the name cannot be used. Unfortunately, I cannot find out who the original author is, nor can I say how long the project has been deleted or abandoned. I have already inquired about this via email, see below.

Best regards, Jendrik A. Potyka.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Upstream: https://gitlab.com/DigonIO/scheduler
Mirror: https://github.com/DigonIO/scheduler

### Contact and additional research

I have contacted the PyPi admins via email to find out why the name is not in use:

_The "scheduler" package used to exist but has been deleted by its owner.
This project may be considered an "abandoned project", ..._

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jpotyka** [comment] 2021-06-07 12:57
Note: The [DigonIO](https://github.com/DigonIO) user is marked as ghost because we transformed it to an organization.

**Comment by yeraydiazdiaz** [comment] 2021-07-18 09:51
I can confirm the project has no releases and is therefore considered invalid, I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment] 2021-07-25 08:00
Transfer complete.

**Closed by yeraydiazdiaz** 2021-07-25 08:00 UTC
Labels: PEP 541

**Comment by jpotyka** [comment] 2021-07-25 11:55
Thank you for the support in the transfer of the project.

Best regards, Jendrik A. Potyka.
