### ISSUE TITLE
PEP 541: casatools

### ISSUE THREAD

**Issue by vsuorant** [pypa/pypi-support#421] opened 2020-05-28 16:56 UTC
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/casatools/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/vsuorant

**Reasons for the request**

casatools project was squatted and is causing problems with our private PyPI repository. We had intended to upload the the project to PyPI but had not yet done so. Partly because we will also need to request extra space in the repository.

**Maintenance or replacement?**

Replace the contents with a wheel built from here:
https://open-bitbucket.nrao.edu/projects/CASA/repos/casatools/browse

**Contact and additional research**

I have emailed the current owner but have not heard anything back yet.

**Comment by yeraydiazdiaz** [comment] 2020-06-06 09:28
Hi @vsuorant, it seems the owner of the project is GitHub user @cowlicks, hopefully we will hear back in regards of this project.

Regarding the reason for squatting in the project's description:

> The problem occurs when --extra-index-url is used to point to a private PyPI that has packages with names shadowed on the public PyPI. When then this happens pip is needs to choose which PyPI to take the package from. It simply chooses the one with the higher version number.

I'm not sure that's correct. I believe when using private PyPI repos the workflow is to use `--index-url` to point to the private PyPI repo combined with `--extra-index-url` to point to PyPI. This will instruct `pip` to only reach for PyPI if no package is found it the private repo.

Again, I'm not 100% sure, but I would double check the [config section of the pip docs](https://pip.pypa.io/en/stable/user_guide/#config-file).

In any case the project is invalid and will be transferred after a one week courtesy period. If the owner does not reply to this issue I will attempt contact via email in the next few days.

**Comment by vsuorant** [comment] 2020-06-08 19:44
Thank you for your help. I haven't heard anything from @cowlicks for more than a week.

> I'm not sure that's correct. I believe when using private PyPI repos the workflow is to use --index-url to point to the private PyPI repo combined with --extra-index-url to point to PyPI. This will instruct pip to only reach for PyPI if no package is found it the private repo.

I am pretty sure that the description by @cowlicks is correct. This is even worse with packages that target only a limited number of platforms or python versions. So for example if there is no compatible package in private PyPI but there is a "none-any" wheel in PyPI, the latter will get installed. And of course using a pypi proxy is out of the question.

**Comment by yeraydiazdiaz** [comment] 2020-06-14 08:38
The courtesy period has passed, I will now ask an admin to perform this transfer for you.

**Comment by vsuorant** [comment] 2020-06-22 17:15
Thank you @yeraydiazdiaz . How long does the transfer typically take at this point?

**Comment by vsuorant** [comment] 2020-07-06 19:44
Any updates on this?

**Comment by cowlicks** [comment] 2020-07-16 19:28
Hi, ryanraba has been added as an owner of "casatools". Sorry for the delay.

**Comment by vsuorant** [comment] 2020-07-20 18:11
Thanks. I believe this now resolved.

**Comment by ewdurbin** [comment] 2020-11-09 15:32
Confirmed that vsuorant and ryanraba are marked as owners on the PyPI project.

**Closed by ewdurbin** 2020-11-09 15:32 UTC
Labels: PEP 541
