### ISSUE TITLE
Mass name squat by user: leesoar

### ISSUE THREAD

**Issue by synchronizing** [pypa/pypi-support#1447] opened 2021-11-03 21:22 UTC
### PyPI user performing the mass project name squatting

https://pypi.org/user/leesoar

### Additional information

Reported user in #1446 as well. Squatting the following packages with no code in them (other than "Develop soon" README):

* `adsl`
* `kwai`
* `ida`
* `cover`
* `trends`
* `netease`
* `beta`
* `enc`
* `am`
* `break`
* `admin`
* `kol`
* `leetcode`
* `xposed`
* `refer`
* `zan`
* `edu`
* `dell`
* `del`
* `night`
* `bcc`
* `nick`
* `adidas`
* `ticket`
* `come`
* `ol`
* `cert`
* `ali`
* `cia`
* `media`
* `alive`
* `gbg`
* `Tyche`
* `Bellona`
* `employ`
* `figlet`
* `ollybd`
* `nintendo`
* `waf`
* `mikufans`
* `ipool`
* `ins`
* `gayhub`

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment] 2022-01-03 19:38
Thanks! This is a duplicate of #557.

**Closed by di** 2022-01-03 19:38 UTC
Labels: mass name squat
