### ISSUE TITLE
PEP 541 Request: PIE

### ISSUE THREAD

**Issue by prashanth-up** [pypa/pypi-support#741] opened 2020-11-16 13:10 UTC
**Project to be claimed**

`pie 0.6`: https://pypi.org/project/pie

**Your PyPI username**

`prashanth_up`: https://pypi.org/user/prashanth_up

**Reasons for the request**

The Project has been abandoned since March 26, 2014. There has been no updates or publishes ever since that date.
I would like to publish my project under the name of `PIE`

**Maintenance or replacement?**
 
Replacement, as there is no files in that user's package.
My code repo : https://github.com/new-git-test/PIE

**Contact and additional research**

I have contacted the user on all platforms possible, but no reply yet.

I would like to present that this issue has been already processed by a maintainer (@yeraydiazdiaz) and no reply from him too after the wait time.
Please review the same issue in the past https://github.com/pypa/pypi-support/issues/381

**Comment by pradyunsg** [comment] 2020-11-16 14:20
Duplicate of #381

**Closed by pradyunsg** 2020-11-16 14:20 UTC
Labels: PEP 541

**Comment by prashanth-up** [comment] 2020-11-16 14:25
@pradyunsg I acknowledge this is a duplicate of my previous issue.
Since I have no response from the original issue I have recreated it for someone to acknowledge it.

Please check out the old issue as the maintainer @yeraydiazdiaz is not replying.
