### ISSUE TITLE
New account verification email not received at outlook.com address

### ISSUE THREAD

**Issue by max-graham** [pypa/pypi-support#271] opened 2020-03-13 04:21 UTC
**Describe the bug**
I just signed up for a PyPI account, but I'm unable to receive the verification email at my outlook.com address. I have re-sent the verification email several times, and tried relogging into my PyPI account as well.

**Expected behavior**
Verification email should be sent to the registered email address when requested.

**My Platform**
@outlook.com email address (maxgraham at outlook dot com)

**Additional context**
This seems to be the same issue as pypa/warehouse#3172 and pypa/warehouse#4009

**Comment by di** [comment] 2020-03-13 15:09
I'm seeing this now with other `@outlook.com` addresses as well as `@hotmail.com` addresses.

This might be a duplicate of https://github.com/pypa/pypi-support/issues/153.

**Comment by max-graham** [comment] 2020-03-13 16:33
@di I just received one verification email at my outlook address. Not sure if that's the first one or the last one that I sent last night, haha.

**Comment by di** [comment] 2020-03-13 17:00
Hmm, looks like it was the 4th out of 5 total. Let's give it a bit more time.

**Comment by di** [comment] 2020-03-16 22:00
In the end, 3/5 of these soft-bounced and 2/5 were delivered, so we might be having deliverability issues with this mail provider. I'm going to call this a duplicate of #153. Thanks for the report!

**Closed by di** 2020-03-16 22:00 UTC
