### ISSUE TITLE
PEP541: Add a maintainer to `sphinxcontrib-domaintools`

### ISSUE THREAD

**Issue by eric-wieser** [pypa/pypi-support#22] opened 2019-07-14 17:44 UTC
The [`sphinxcontrib-domaintools`](https://pypi.org/project/sphinxcontrib-domaintools/) package on PyPI is backed by https://github.com/sphinx-contrib/domaintools, for which @klorenz and @tk0miya have commit rights.

The package no longer works with recent python3 or pip, and while there are PRs to fix those problems, the only PyPI maintainer, @klorenz, is unfortunately not responsive. @tk0miya [points out](https://github.com/sphinx-contrib/domaintools/pull/4#issuecomment-509730883) that while they can merge the PRs, they would not have the ability to publish to PyPI.

The easiest way out of this situation would be to add @tk0miya as a maintainer on PyPI. I'll let @tk0miya confirm that this is desirable. I haven't successfully made contact with @klorenz when asking this question.

**Comment by klorenz** [comment] 2019-11-06 19:25
Hi Eric, Just reviewed my mails. What can I do to help you resolving this
issue. I do not have the time to take care for the package on s regular
base.

Best regards, Kiwi

Eric Wieser <notifications@github.com> schrieb am Fr., 25. Okt. 2019, 22:38:

**Comment by jamadden** [comment] 2019-11-06 21:39
Hi @klorenz,

> What can I do to help you resolving this issue

If @tk0miya provides you with their PyPI username, you could add that account as an additional maintainer for the sphinxcontrib-domaintools project by logging into pypi.org.

**Comment by tk0miya** [comment] 2019-11-07 13:47
Hi @klorenz , this is my account: https://pypi.org/user/tk0miya/
Could you add me to co-maintainer list?
Thanks,

**Comment by klorenz** [comment] 2019-11-08 11:11
Hi Takeshi,

I have added you.

Best regards,

Kiwi

Takeshi KOMIYA <notifications@github.com> schrieb am Do., 7. Nov. 2019,
14:47:

**Comment by jamadden** [comment] 2019-11-10 15:52
This seems to be resolved so I'm closing the issue.

**Closed by jamadden** 2019-11-10 15:52 UTC
Labels: PEP 541

**Comment by tk0miya** [comment] 2019-11-17 06:55
@klorenz @eric-wieser  Confirmed. Thank you for your time. I'll try to keep it maintained as possible.
@jamadden Thank you for support!

Thank you all!
