### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ptmcg** [pypa/pypi-support#2211] opened 2022-09-05 12:57 UTC
### PyPI Username

ptmcg

### Reason for request

2FA auth data did not transfer over to new phone. PyPI was one of the first applications I set up with 2FA, and I did not appreciate the importance of the recovery codes, so I did not generate any.

I have a new release of pyparsing to push out soon, and I think this may prevent me from doing so.

I still have the email address attached to this account, as well as my phone number.

Thanks so much for your attention!

-- Paul

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2022-10-12 19:59
Closing as duplicate of #2075

**Closed by ewdurbin** 2022-10-12 19:59 UTC
Labels: account-recovery
