### ISSUE TITLE
A lot of "reserved" projects by user acue

### ISSUE THREAD

**Issue by ldng** [pypa/pypi-support#397] opened 2020-05-18 20:47 UTC
The user acue (https://pypi.org/user/acue/) has reserved a lot of project and that is polluting searches all over the place. Something should probably be done about that.

**Comment by jorgecarleitao** [comment] 2020-10-14 03:36
related #536

**Comment by yeraydiazdiaz** [comment] 2021-05-13 11:18
Closing as duplicate of #536

**Closed by yeraydiazdiaz** 2021-05-13 11:18 UTC
