### ISSUE TITLE
PEP 541 Request: PyUI

### ISSUE THREAD

**Issue by dcwatson** [pypa/pypi-support#386] opened 2020-05-14 19:12 UTC
**Project to be claimed**

`PyUI`: https://pypi.org/project/PyUI

**Your PyPI username**

`dcwatson`: https://pypi.org/user/dcwatson

**Reasons for the request**

I think this package could be considered either abandoned or invalid under PEP 541. I don't believe this was name squatting, as http://pyui.sourceforge.net exists, but the package on PyPI was created in 2003 and has no downloadable releases. The SF site does not have a date on it, but does mention having a Windows 2000 theme. Unfortunately, I don't have a CVS client handy to check when the last commit was.

**Maintenance or replacement?**

I hope to publish a new package that (unsurprisingly) is a cross-platform UI framework for Python. Given that it's loosely modeled on SwiftUI, the name is just too good not to try for.

https://github.com/dcwatson/pyui
https://pyui.net

**Contact and additional research**

I emailed the maintainer listed on the current PyPI listing (and the SF website) back in March:

    Date: Fri, 13 Mar 2020 17:39:53 -0400
    Message-ID: <CA+ZOytn2qZX2wzUnuiqkccL79sZyv+EtbT_ZG27A7mV8nNivCA@mail.gmail.com>
    Subject: PyUI on PyPI
    From: Dan Watson <dcwatson@gmail.com>
    To: sean@twistedmatrix.com

    Hi Sean,

    I'm writing to see if you had any future plans for the "PyUI" name on PyPI.
    More specifically, if you don't, I have a project I'd love to use it for:

    https://github.com/dcwatson/pyui

    I can certainly release under a different name, but I figured the pyui name
    on PyPI is currently defunct, so maybe you wouldn't mind if I gave it a run?

    Best,
    Dan Watson

Considering it's a twistedmatrix email address, and Twisted's notoriety in the Python community, I wonder if anyone here may know other ways to reach the author. I didn't see Sean on https://github.com/orgs/twisted/people though.

**Comment by yeraydiazdiaz** [comment] 2020-05-27 08:23
Hi @dcwatson, I can confirm PyUI has a single release with no files and is therefore considered invalid.

In these cases we attempt contact with the owner to give a one week courtesy period before transferring the project, the PyPI owner had a different email address to the one @twistedmatrix so we may hear back, otherwise we can move forwards with the transfer.

**Comment by yeraydiazdiaz** [comment] 2020-06-06 08:30
The courtesy period has passed, I will now ask an admin to perform the transfer for you.

**Comment by ewdurbin** [comment] 2020-11-09 15:29
Transfer complete.

**Closed by ewdurbin** 2020-11-09 15:29 UTC
Labels: PEP 541

**Comment by dcwatson** [comment] 2020-11-09 18:24
Thank you both!

**Comment by zainhoda** [comment] 2023-03-17 19:28
Hello @dcwatson -- it appears that you haven't released anything using the PyUI package. I was wondering if you would be open to transferring the package to me? I have a web UI library that I would like to release under that name. 

I'm commenting here because the e-mail address listed on https://pypi.org/project/PyUI/ is still the old owner's.

I have extracted the HTML Web UI components from my existing Python package and I'm ready to release it as it's own separate package: https://pypi.org/project/pycob/

I would love it if I could release those UI components as PyUI.

Thanks!

**Comment by dcwatson** [comment] 2023-03-17 23:02
Sorry, I thought I had already published it - turns out I had to delete the old version that was up there with no files. Anyway, I already had the site up, and I fixed the published version.
