### ISSUE TITLE
PEP 541 Request: Aztec

### ISSUE THREAD

**Issue by isidentical** [pypa/pypi-support#392] opened 2020-05-16 14:05 UTC
**Project to be claimed**

`aztec`: https://pypi.org/project/aztec

**Your PyPI username**

`BTaskaya`: https://pypi.org/user/BTaskaya

**Reasons for the request**

It is been there for 8 years without any real code, or releases. The github page (linked as homepage) is a dead link.

**Maintenance or replacement?**

Replacement with a brand new library for [AST acceleration](https://github.com/isidentical/aztec)
**Contact and additional research**

I've sent an email earlier, but didn't get a response. I'm not sure if the original claimer of this package still uses that email or not.

**Comment by yeraydiazdiaz** [comment] 2020-05-27 08:43
Hi @isidentical, I can confirm `aztec` has a single release with no files and is therefore considered invalid.

In these cases we attempt contact with the owner and allow a one week courtesy period before transferring the project. Looks like GitHub user @lishnih is the owner of the project, I will also attempt contact via email.

**Comment by yeraydiazdiaz** [comment] 2020-05-27 09:30
The owner replied accepting the transfer, I will now ask an admin to perform the transfer for you.

**Comment by ewdurbin** [comment] 2020-11-09 15:25
Transfer complete.

**Closed by ewdurbin** 2020-11-09 15:25 UTC
Labels: PEP 541

**Comment by isidentical** [comment] 2020-11-09 15:27
Thanks!
