### ISSUE TITLE
PEP 541 request: hangul

### ISSUE THREAD

**Issue by noyongkyoon** [pypa/pypi-support#778] opened 2020-12-04 09:14 UTC
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/hangul

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/noyongkyoon

**Reasons for the request**

Project is invalid: it is name squatting.Package has no functionality.

**Maintenance or replacement?**

Current package will be replaced with the following package:

[hangul](https://test.pypi.org/project/hangul/1.0b5/)

**Contact and additional research**

I wrote a letter to the current owner but have had no response from him.

> 김경훈 선생님께
> 선생님께서 6년 전에 시작하신 pypi 프로젝트 hangul은 어떤 알맹이가 없는 상태인 것으로 보입니다.
> 어떤 왕성한 활동이 일어나지 않고 있으며 버전 0.1 이후에 어떤 버전도 추가되지 않았습니다.
> 다른 유용한 사용을 위해 이 프로젝트 이름을 내어 놓는 것을 고려해 주시면 고맙겠습니다.
> 노용균 드림
> 충남대학교 언어학과 교수

I have been doing research in nlp in general and in Korean (and hangul) in particular.

* [My paper on parsing](https://www.aclweb.org/anthology/Y07-1037/)
* [My paper on word segmentation](http://mlp.computing.dcu.ie/mlp2017/docs/proceeding.pdf)

**Comment by yeraydiazdiaz** [comment] 2021-05-13 10:35
Hello @noyongkyoon, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week before transferring it.

**Comment by yeraydiazdiaz** [comment] 2021-05-13 10:38
Tagging GitHub user @koorukuroo who appears to be the author of the project, I will be considering this the courtesy contact attempt.

**Comment by koorukuroo** [comment] 2021-05-20 03:03
Oh I'm sorry to check late.
I tend to not see notifications because there are so many notifications on GitHub.

Thank you for your suggestion @noyongkyoon, the letter means email? but not received.

Anyway, I agree the destroy the package https://pypi.org/project/hangul
and thank you for contributing to the analysis of Korean @noyongkyoon 👍 

I'm happy to keep an eye on your project. Thank you!

**Comment by koorukuroo** [comment] 2021-05-20 03:07
I deleted the project `hangul`
Plz check and close issue. :)

**Comment by yeraydiazdiaz** [comment] 2021-05-20 07:56
Thank you @koorukuroo

**Closed by yeraydiazdiaz** 2021-05-20 07:56 UTC
Labels: PEP 541

**Comment by noyongkyoon** [comment] 2021-05-20 09:21
Thank you very much Mr. Kyunghoon Kim and Mr. Yeray Diaz.

I will try to upload my work toproject hangul in a couple of days.
Please keep up the good work you have been doing for the community.

Thanks again

2021년 5월 20일 (목) 오후 4:57, Yeray Diaz Diaz ***@***.***>님이 작성:
