### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by samuelcorradi** [pypa/pypi-support#1399] opened 2021-10-20 10:37 UTC
### PyPI Username

samuelcorradi

### Reason for request

Hi! I probably enabled two-factor authentication and didn't save the code as it's not in my application. I can no longer access my account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2021-11-08 18:31
above action not taken as this is a duplicate of #1239

**Closed** 2021-11-08 18:31 UTC
Labels: account-recovery
