### ISSUE TITLE
Limit Request: paddlepaddle_gpu - 800 MB

### ISSUE THREAD

**Issue by zhouwei25** [pypa/pypi-support#677] opened 2020-10-19 08:36 UTC
**Project**

https://github.com/PaddlePaddle/Paddle
https://pypi.org/project/paddlepaddle-gpu/

**Size of release/project**

800MB

**Which indexes**

PyPI

**Reasons for the request**

We will release a new version for paddlepaddle_gpu recently. Our current size limit is 600M, and the dev version is 660M. Because a few new features are enabled in this version, and most of the new feature is new operate op (200 new api )with cuda and cudnn and the cuda c++ dll has a large size in windows , so the size increase quickly. Can you please help to increase this to around 800MB.

It's very urgent. Thank you very much! 

-- PaddlePaddle Team

**Comment by di** [comment] 2020-11-19 16:10
Duplicate of https://github.com/pypa/pypi-support/issues/663.

**Closed by di** 2020-11-19 16:10 UTC
Labels: limit request
