### ISSUE TITLE
PEP 541 Request: WikiExtractor

### ISSUE THREAD

**Issue by attardi** [pypa/pypi-support#605] opened 2020-09-07 14:57 UTC
**Project to be claimed**
PROJECT_NAME: https://pypi.org/project/wikiextractor

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/attardi

**Reasons for the request**
I have already created an issue of this (https://github.com/pypa/pypi-support/issues/510), but no action has been taken so far.

This is the original motivation:
I am the developer of the Wikiextractor package (https://github.com/attardi/wikiextractor) from which mAboshokor created the PyPi project.

**Maintenance or replacement?**
I would like to replace the project with a newest version, with better description and uptodate releases.

**Contact and additional research**
An attempt was made to contact the current owner, mAboshokor , but that has been unsuccessful.

**Comment by jamadden** [comment] 2020-09-07 15:22
Closing as a duplicate of #510. Please do not open duplicate issues.

**Closed** 2020-09-07 15:21 UTC
Labels: PEP 541

**Comment by attardi** [comment] 2020-09-07 15:29
Can you please take action on https://github.com/pypa/pypi-support/issues/510?
Thanks.

**Comment by jamadden** [comment] 2020-09-07 16:56
The administrators are aware of it and will perform the transfer when possible. There is nothing further you or I can do.
